on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build app
        run: ./scripts/buildprod.sh

      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true # This line is important

      - name: Build docker image
        run: gcloud builds submit --project notely-413719 --tag us-central1-docker.pkg.dev/notely-413719/notely-ar-docker/notely:latest .
